### ISSUE TITLE
Training Deep Networks with Synthetic Data: Bridging the Reality Gap by Domain Randomization

### ISSUE THREAD

**Issue by tk-01** [yuuy-git/papers#10]
https://arxiv.org/abs/1804.06516

#What
This paper comes from Nvidia and goes full throttle on using synthetic data to train Convolutional Neural Networks (CNNs). They created a plugin for Unreal Engine 4 which will generate synthetic training data. 

#Why 
Certified Nerd says it is the 10 coolest papers from CVPR 2018
https://towardsdatascience.com/the-10-coolest-papers-from-cvpr-2018-11cb48585a49

**Comment by rchavezj** [comment]
I'm trying to wrap my head around why this paper is useful. It looks cool.

**Comment by yuchen-xue** [comment]
So does this plugin open to the public?
