### ISSUE TITLE
Synthesizing Images of Humans in Unseen Poses

### ISSUE THREAD

**Issue by tk-01** [yuuy-git/papers#5]
https://arxiv.org/abs/1804.07739

# What
人間のSource Imageと変えたい姿勢のTarget Pose（棒人間で身体のパーツが分けられた素材）をInputに入れると、人間がその姿勢をしている画像が生成される。
人物を取り除いた背景画像と、姿勢を変えた人物の画像をそれぞれ予測し、組み合わせて画像を生成してる？
pose2img系の最新。

# Why
CVPR2018の論文紹介のツイートで面白そうだったので。

**Comment by tk-01** [comment]
日本語で所感をまとめたgitがあった
https://github.com/DwangoMediaVillage/paper_readings/issues/41
というかこれくらいしか日本語の情報がなかった

**Comment by sanshin5050** [comment]
複雑な問題をかみ砕いて一つ一つ処理するだけで論文になるってやっぱ基礎力大事やなと
基礎ができて論理的思考ができればこういう論文かけそうやな
